name: Publish library

on:
  release:
    types:
      - published

jobs:
  package:
    runs-on: ubuntu-latest
    name: Build and deploy to Github Packages

    steps:
      - uses: actions/checkout@v2

      - name: 'Use Node.js 12.x'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@juraji'

      - name: Yarn install cache
        uses: c-hive/gha-yarn-cache@v1

      - name: 'Install dependencies'
        run: yarn --frozen-lockfile

      - name: 'Build package'
        run: npx ng build modals --prod

      - name: 'Publish package'
        run: yarn publish dist/modals --new-version "${GITHUB_REF:11}" --no-git-tag-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
